### ISSUE TITLE
Where can I get “wikipedia documents” ? 

### ISSUE THREAD

**Issue by bultiful** [THUDM/CogQA#22] opened 2020-07-10 08:20 UTC
Hi , Where can I get “wikipedia documents” ? 
 [step 4 of Preprocess ：Run python read_fullwiki.py to load wikipedia documents to redis ]

**Comment by Sleepychord** [comment] 2020-07-10 08:35
Duplicate of #11 , you can find them in https://hotpotqa.github.io/wiki-readme.html

**Closed as completed by Sleepychord** 2020-07-10 08:35 UTC

**Comment by bultiful** [comment] 2020-07-10 08:57
thx u !
